<a href="https://colab.research.google.com/github/YeabAM/ML-Practice/blob/main/Yeabkalu_Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [ ]:
#your code here
import itertools

letters = ['A','B','C']

all_combination = list(itertools.combinations(letters, 2))
print(all_combination)

[('A', 'B'), ('A', 'C'), ('B', 'C')]


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
#your code here
sequence =  ['Python', 'is', 'fun']
inf_seq = itertools.cycle(sequence)

for _ in range(10):
  print(next(inf_seq))

Python
is
fun
Python
is
fun
Python
is
fun
Python


In [ ]:
#creating a py file for the next checkpoint and I am using writefile magic command
%%writefile test.py

# Contents of the test.py file
print("Hello, world!")


Overwriting test.py


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [ ]:
#your code here
import os, glob
current_dir = os.getcwd()
pattern = '*.py'
file_pattern = os.path.join(current_dir,pattern)

py_files = glob.glob(file_pattern)

for file in py_files:
  print(file)

/content/test.py


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
html_doc = """
<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>
"""
#install beautifulsoup using pip
!pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#your code here
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc, 'html.parser')
p_tags = soup.find_all('p')

for p_tag in p_tags:
  print(p_tag.get_text())


AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [ ]:
#define a function that replace the word using a replacement pattern in the given text
import re

def replace_word(text, replacements):
    for word, replacement in replacements.items():
        pattern = r'\b' + re.escape(word) + r'\b'
        text = re.sub(pattern, replacement, text)
    return text

In [ ]:

text = "AI is transforming the world."
replacements = {
    'AI': 'Artificial Intelligence'
}
new_text = replace_word(text, replacements)
print("old text: ", text)
print("new text: ", new_text)


old text:  AI is transforming the world.
new text:  Artificial Intelligence is transforming the world.


**CP6**: Create a numpy array of 10 zeros.

In [ ]:
#your code here
import numpy as np
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [ ]:
#your code here
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [ ]:
#your code here
array = np.arange(0, 9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

**Explanation**:
Machine Learning models work using by building a mathemetical pattern from the given data and and deep learning they use neural network to do that in a more sophisticated way. So the for the model to have a greater accuracy, the quality and quantity of the data have direct effect. This means that the larger the data it is trained upon the more reliable and accurate the model becomes.
The next question is what does **large** mean:
Data is large if the amount if big enough in terms of quantity. It most importantly means have greater amount of variety and diversity in it which also makes the model to predict in better accuracy. This will help the model prevent it from overfitting and enough dataset will be there to split it in reasonable manner to testing and training sets

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

There are several ways AI can be used in adverserial way:


*   DeepFakes: With high advancement in computer vision, we are able to recreate characters and faces that look so real to the real people and indistinguishable from the real person. This can be used to spread false information by mimicking reliable and relevant personnel
*   Models can be poisined with wrong information to morph and teach them to spread false information

The above can be prevent by using different anomaly detection algorithms that can detect such adeverserial activities, we can also do adverserrial training on the model so that it can recognise malicious activities and we can already see it in ChatGPT where if it is asked to do some illegal activities, it will understand it and refuses to proceed. These are just examples to make sure that the AI is as safe as possible

